# Generated by Django 5.1.5 on 2025-02-03 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OTM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('title', models.CharField(max_length=255, verbose_name='OTM nomi')),
            ],
            options={
                'verbose_name': 'OTMlar',
                'verbose_name_plural': 'OTMlar',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqam')),
                ('amount', models.IntegerField(verbose_name='Summa')),
                ('payment', models.CharField(choices=[('NQ', 'Naqd pul'), ('CD', 'Plastik karta'), ('PK', "Pul ko'chirish")], default='CD', max_length=2, verbose_name="Tolo'v usuli")),
                ('sponsor_type', models.CharField(choices=[('YSH', 'Yuridik shaxs'), ('JSH', 'Jismoniy shaxs')], default='JSH', max_length=3, verbose_name='Homiy turi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Izoh')),
                ('status', models.CharField(choices=[('NEW', 'Yangi'), ('MD', 'Moderatsiyada'), ('CONFIRMATION', 'Tasdiqlangan'), ('CANCEL', 'Bekor qilingan')], default='New', max_length=20)),
            ],
            options={
                'verbose_name': 'Homiylar',
                'verbose_name_plural': 'Homiylar',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('full_name', models.CharField(max_length=255, verbose_name='F.I.SH')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Telefon raqam')),
                ('student_type', models.CharField(choices=[('BR', 'Bakalavr'), ('MA', 'Magistratura')], max_length=2, verbose_name='Talaba turi')),
                ('contract_amount', models.IntegerField(verbose_name='Kontart summa')),
                ('otm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='app.otm', verbose_name='OTM ni tanlang')),
            ],
            options={
                'verbose_name': 'Talabalar',
                'verbose_name_plural': 'Talabalar',
            },
        ),
        migrations.CreateModel(
            name='SponsorAdd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan sana')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan sana")),
                ('allocated_amount', models.IntegerField(verbose_name='Ajratilgan summa')),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocated_funds', to='app.sponsor', verbose_name='Homiy')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsorships', to='app.student', verbose_name='Talaba')),
            ],
            options={
                'verbose_name': "Homiy qo'shish",
                'verbose_name_plural': "Homiy qo'shish",
            },
        ),
    ]
