# Generated by Django 5.1.5 on 2025-02-05 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sponsor',
            old_name='payment',
            new_name='payment_type',
        ),
        migrations.RenameField(
            model_name='sponsor',
            old_name='sponsor_type',
            new_name='type',
        ),
        migrations.RemoveField(
            model_name='sponsor',
            name='description',
        ),
        migrations.AddField(
            model_name='sponsor',
            name='org_name',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=20, verbose_name='Telefon raqam'),
        ),
    ]
